### ISSUE TITLE
Basic usage example

### ISSUE THREAD

**Issue by robmarkcole** [dicompyler/dicompyler-core#4] opened 2016-10-04 11:40 UTC
Following [https://github.com/dicompyler/dicompyler-core#basic-usage](url)
At 

`dvh = dvh.DVH.from_dicom_dvh(rtdose.ds, 5)`

I get error

`/Users/..../python3.5/site-packages/dicompyler_core-0.5.2-py3.5.egg/dicompylercore/dvh.py in statistic(self, name)
    
484         # print(match.groups())
485         if not match or match.groups()[0] is not None:
--> 486             raise AttributeError("'DVH' has no attribute '%s'" % name)
487 
488         # Process the regex match

AttributeError: 'DVH' has no attribute 'DVH'`

**Comment by robmarkcole** [comment] 2016-10-04 12:02
However recreating your working in **dicompyler-core_usage.ipynb** I have no problems at 

heart = rtdose.GetDVHs()[key]
heart.name = structures[key]['name']
heart.describe()

Structure: Heart
-----
DVH Type:  cumulative, abs dose: Gy, abs volume: cm3
Volume:    437.46 cm3
Max Dose:  3.10 Gy
Min Dose:  0.02 Gy
Mean Dose: 0.64 Gy
D100:      0.00 Gy
D98:       0.03 Gy
D95:       0.03 Gy
D2cc:      2.93 Gy

**Comment by bastula** [comment] 2016-10-04 18:45
I just tried the basic usage steps in a new Python interpreter session and I am unable to reproduce your error.

The only way to get that assertion is if the first argument to `from_dicom_dvh` is _not_ a `pydicom` dataset. Try making sure that you are passing in a `pydicom` dataset to the method.

Also, the code in basic usage and in the notebook should be almost identical for setup.

**Comment by bastula** [comment] 2016-10-04 18:55
✋  😔  I found the bug. In the basic usage, I'm overwriting the dvh module in memory with the dvh variable. In the notebook, the variable is named `heart`.

Therefore if you run the code snippet again (2nd or 3rd time, etc.), it won't work! I'll change the documentation to reflect this.

Thanks for the catch! 👍

**Comment by bastula** [comment] 2016-10-04 19:30
Closed by #5.

**Closed by bastula** 2016-10-04 19:30 UTC
